### ISSUE TITLE
Measuring vertical video

### ISSUE THREAD

**Issue by Ruthfliflu** [egemose/DroneVideoMeasure#5]
Hi,
I'm just starting to use the drone video measure to analyze a few videos but i'm finding out that i can only work with horizontal videos, when I upload any vertical videos it doesn't show me the full image of the video. I tried to rotate some but I'm afraid that it streches the video and the measure is no longer good and also it would take me ages to do that with all of them. 
So is there something that i can do to work with vertical videos??

**Comment by henrikmidtiby** [comment]
Thanks for reaching out about the Drone Video Measure tool.
Can you provide some more detail about the videos that you want to analyze? 
How have the videos been recorded?
From the above description, I assume that the videos are oriented in portrait mode (where the video is higher that its width).

You can also sent this information to my email hemi@mmmi.sdu.dk if you do not want to mention it here.
